from building import *

cwd = GetCurrentDir()

src = Glob('*.cpp')

CPPPATH = [cwd]

group = DefineGroup('JerryScript_demo_addCpp', src, depend = ['PKG_USING_JERRYSCRIPT'], CPPPATH = CPPPATH)

Return('group')
